/* Note : Generated By a LLM */
export const formatVideoDuration = (duration: string): string => {
  // Convert the string to a number (duration in seconds)
  const durationInSeconds = parseFloat(duration);

  // Validate the input
  if (isNaN(durationInSeconds) || durationInSeconds < 0) {
    return "00:00"; // Fallback for invalid durations
  }

  // Round to the nearest whole second
  const totalSeconds = Math.round(durationInSeconds);
  const hours = Math.floor(totalSeconds / 3600);
  const minutes = Math.floor((totalSeconds % 3600) / 60);
  const seconds = totalSeconds % 60;

  // Format as HH:MM:SS if there are any hours, otherwise MM:SS
  if (hours > 0) {
    return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(
      2,
      "0"
    )}:${String(seconds).padStart(2, "0")}`;
  } else {
    return `${String(minutes).padStart(2, "0")}:${String(seconds).padStart(
      2,
      "0"
    )}`;
  }
};
